# Generated by Django 2.2.6 on 2020-01-03 06:08

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrations',
            fields=[
                ('profile_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/profiles')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('Comments', models.CharField(max_length=1000, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'illustrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photographies',
            fields=[
                ('profile_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/profiles')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'photographies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('photos', models.ManyToManyField(related_name='photos', to='hobbies.Photographies')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
