# Generated by Django 2.2.6 on 2020-01-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illstrations',
            name='Comments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='illstrations',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
