# Generated by Django 2.2.6 on 2020-01-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustrations',
            options={'managed': True, 'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['-created_on']},
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
