# Generated by Django 2.2.6 on 2020-01-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_auto_20200103_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustrations',
            options={'managed': True, 'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='illustrations',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
