# Generated by Django 2.2.6 on 2020-01-02 09:55

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_auto_20200102_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='illustrations',
            fields=[
                ('profile_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/profiles')),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('Comments', models.CharField(max_length=1000, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'illstrations',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Illstrations',
        ),
    ]
