# Generated by Django 2.2.6 on 2020-01-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_auto_20200102_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustrations',
            name='priority',
        ),
    ]
